# **Tableau numpy**
### **Importation Numpy**

In [1]:
import numpy as np

In [3]:
ar = np.array([1,2,3,4])
ar.dtype

dtype('int32')

In [5]:
print(f"dimension : {ar.ndim}, taille : {ar.size}, forme : {ar.shape}")

dimension : 1, taille : 4, forme : (4,)


### **Tableau numpy a multi-dimenssion**

In [10]:
ar1 = np.array([[1,2,3],[4,5,6]])
ar1

array([[1, 2, 3],
       [4, 5, 6]])

Un accès par une seule paire de crochets avec des indices séparés par des virgules

In [11]:
ar1[0,0] = 7
ar1

array([[7, 2, 3],
       [4, 5, 6]])

les tableaus numpy ont un type fixe

In [13]:
print(ar1.dtype)
b = np.array([1, 2, 3], dtype=np.float32)
print(b.dtype) 
ar1[0,0] = np.pi
ar1

int32
float32


array([[3, 2, 3],
       [4, 5, 6]])

### **Décomposition :**
    np.arange(start, stop, step) est une fonction NumPy qui crée un tableau 1D avec des valeurs régulièrement espacées.
    - start = 0 → le point de départ
    - stop = 20 → non inclus (attention : comme range() en Python)
    - step = 3 → le pas entre les valeurs

In [16]:
ar2 = np.arange(0,20,3)
ar2

array([ 0,  3,  6,  9, 12, 15, 18])

In [17]:
ar3 = ar2[:5]
ar3

array([ 0,  3,  6,  9, 12])

In [18]:
ar3[:4:2]

array([0, 6])

In [19]:
ar1.shape

(2, 3)

### **reshape(m, n)**

    → donne un tableau de forme (m, n)
    → Ne change pas les valeurs, juste la structure
    → Crée un nouveau tableau (pas en place sauf si réaffecté à ar1)

In [21]:
ar4 = ar1.reshape(3,2)
ar4

array([[3, 2],
       [3, 4],
       [5, 6]])

## **Concatenation et division**

In [22]:
tab1 = np.array([1,2,3,4])
tab = np.concatenate([tab1, tab1])
tab

array([1, 2, 3, 4, 1, 2, 3, 4])

In [23]:
tab2 =  np.array([[1,2,3],[4,5,9]])
tabs = np.concatenate([tab2, tab2])
tabs

array([[1, 2, 3],
       [4, 5, 9],
       [1, 2, 3],
       [4, 5, 9]])

**Concatène deux copies d'un tableau horizontalement (côte à côte), c’est-à-dire le long de l’axe des colonnes (`axis=1`).**

- le tableau doit avoir le même nombre de lignes dans les deux instances.


In [24]:
tab3 =  np.concatenate([tab2,tab2], axis = 1)
tab3

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 9, 4, 5, 9]])

La fonction `np.vstack([...])` concatène les deux tableaux **verticalement** (axe 0), c’est-à-dire en ajoutant les lignes de `tab2` à celles de `tab1[1:]`.

- Les deux tableaux doivent avoir **le même nombre de colonnes**.

In [28]:
np.vstack([tab1[1:], tab2])

array([[2, 3, 4],
       [1, 2, 3],
       [4, 5, 9]])

In [31]:
tab4 = np.hstack([tab3, np.array([[1],[2]])])
tab4

array([[1, 2, 3, 1, 2, 3, 1],
       [4, 5, 9, 4, 5, 9, 2]])

**Diviser un tableau en trois sous-tableaux à l'aide de `np.split` (axe 0 par defaut).**

- le tableau doit avoir **au moins autant de lignes que le plus grand indice de découpe**.


In [39]:
tab5 = np.arange(0,20,3)
a1,a2,a3 = np.split(tab5, [2,4])
print(f"tab5 : {tab5}\na1 : {a1}\na2 : {a2}\na3 : {a3}")

tab5 : [ 0  3  6  9 12 15 18]
a1 : [0 3]
a2 : [6 9]
a3 : [12 15 18]


In [40]:
b1, b2 = np.vsplit(tab3, [1])
print(f"tab3 : {tab3}\nb1 : {b1}\nb2 : {b2}")

tab3 : [[1 2 3 1 2 3]
 [4 5 9 4 5 9]]
b1 : [[1 2 3 1 2 3]]
b2 : [[4 5 9 4 5 9]]


In [42]:
c1, c2 = np.hsplit(tab4, [4])
print(f"tab4 : {tab4}\nc1 : {c1}\nc2 : {c2}")

tab4 : [[1 2 3 1 2 3 1]
 [4 5 9 4 5 9 2]]
c1 : [[1 2 3 1]
 [4 5 9 4]]
c2 : [[2 3 1]
 [5 9 2]]


In [47]:
tab4.transpose()

array([[1, 4],
       [2, 5],
       [3, 9],
       [1, 4],
       [2, 5],
       [3, 9],
       [1, 2]])

In [49]:
np.save('exemple.numpy',tab5)

In [50]:
tab6 = np.load('exemple.numpy.npy')
tab6

array([ 0,  3,  6,  9, 12, 15, 18])