# **Importation Numpy**

In [1]:
import numpy as np

In [3]:
ar = np.array([1,2,3,4])
ar.dtype

dtype('int32')

In [5]:
print(f"dimension : {ar.ndim}, taille : {ar.size}, forme : {ar.shape}")

dimension : 1, taille : 4, forme : (4,)


# **Tableau numpy a multi-dimenssion**

In [10]:
ar1 = np.array([[1,2,3],[4,5,6]])
ar1

array([[1, 2, 3],
       [4, 5, 6]])

Un accès par une seule paire de crochets avec des indices séparés par des virgules

In [11]:
ar1[0,0] = 7
ar1

array([[7, 2, 3],
       [4, 5, 6]])

les tableaus numpy ont un type fixe

In [13]:
print(ar1.dtype)
b = np.array([1, 2, 3], dtype=np.float32)
print(b.dtype) 
ar1[0,0] = np.pi
ar1

int32
float32


array([[3, 2, 3],
       [4, 5, 6]])

## **Décomposition :**
    np.arange(start, stop, step) est une fonction NumPy qui crée un tableau 1D avec des valeurs régulièrement espacées.
    - start = 0 → le point de départ
    - stop = 20 → non inclus (attention : comme range() en Python)
    - step = 3 → le pas entre les valeurs

In [16]:
ar2 = np.arange(0,20,3)
ar2

array([ 0,  3,  6,  9, 12, 15, 18])

In [17]:
ar3 = ar2[:5]
ar3

array([ 0,  3,  6,  9, 12])

In [18]:
ar3[:4:2]

array([0, 6])

In [19]:
ar1.shape

(2, 3)

## **reshape(m, n)**

    → donne un tableau de forme (m, n)
    → Ne change pas les valeurs, juste la structure
    → Crée un nouveau tableau (pas en place sauf si réaffecté à ar1)

In [21]:
ar4 = ar1.reshape(3,2)
ar4

array([[3, 2],
       [3, 4],
       [5, 6]])